const ToDoActionTypes = {
    FETCH_TODO_START: 'FETCH_TODO_START',
    FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
    FETCH_TODO_FAILURE: 'FETCH_TODO_FAILURE',
    ADD_TODO_ITEM: 'ADD_TODO_ITEM',
    REMOVE_TODO_ITEM: 'REMOVE_TODO_ITEM',
    ADD_TODO_TO_DONE: 'ADD_TODO_TO_DONE',
    REMOVE_DONE_ITEM: 'REMOVE_DONE_ITEM'
};

export default ToDoActionTypes;

